# Generated by Django 3.1.3 on 2020-11-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDI_project', '0002_imagemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
